services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${FRONTEND_CONTAINER}
    restart: unless-stopped
    networks:
      - spotifew-network
    environment:
      - VITE_PORT=${VITE_PORT}
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN}
      - DOMAIN=${DOMAIN}
      - NODE_ENV=${NODE_ENV}
      - VITE_API_URL=${VITE_API_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_DOMAIN}`)"
      - "traefik.http.routers.frontend.entryPoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=${VITE_PORT}"
      - "traefik.http.services.frontend.loadbalancer.server.scheme=http"

  proxy:
    image: traefik
    container_name: ${TRAEFIK_CONTAINER}
    restart: unless-stopped
    networks:
      - spotifew-network
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}"
      - "--entrypoints.websecure.http.tls.domains[1].main=${FRONTEND_DOMAIN}"
    volumes:
      - "./data/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.api.entryPoints=websecure"
      - "traefik.http.routers.api.service=api@internal"
    ports:
      - "443:443"
      - "80:80"
    environment:
      - "DUCKDNS_TOKEN=${DUCKDNS_TOKEN}"

networks:
  spotifew-network:
    driver: bridge
